spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/promator}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:1234}

api:
  security:
    token:
      secret: ${TOKEN_SECRET:123456789}