spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/promator?createDatabaseIfNotExist=true}
    username: ${DB_USER:root}
    password: ${DB_PASS:1234}